language: php
php:
  - 7.2

before_install:
  # Turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  # Composer
  - travis_retry composer install --no-progress --prefer-dist

jobs:
  include:
    - script:
        - make tests

    - stage: Quality Assurance
      php: 7.2
      script:
        - make qa

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
