language: php
php:
  - 7.2

before_install:
  # Turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  # Composer
  - travis_retry composer install --no-progress --prefer-dist

script:
  # Tests
  - make tests

jobs:
  include:
    - stage: Quality Assurance
      php: 7.2
      script:
        - make qa

    - stage: Phpstan
      php: 7.2
      script:
        - make phpstan

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
